// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: collections_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - qdrant.Collections

/// Namespace containing generated types for the "qdrant.Collections" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Qdrant_Collections: Sendable {
    /// Service descriptor for the "qdrant.Collections" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Get" metadata.
        public enum Get: Sendable {
            /// Request type for "Get".
            public typealias Input = Qdrant_GetCollectionInfoRequest
            /// Response type for "Get".
            public typealias Output = Qdrant_GetCollectionInfoResponse
            /// Descriptor for "Get".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "Get"
            )
        }
        /// Namespace for "List" metadata.
        public enum List: Sendable {
            /// Request type for "List".
            public typealias Input = Qdrant_ListCollectionsRequest
            /// Response type for "List".
            public typealias Output = Qdrant_ListCollectionsResponse
            /// Descriptor for "List".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "List"
            )
        }
        /// Namespace for "Create" metadata.
        public enum Create: Sendable {
            /// Request type for "Create".
            public typealias Input = Qdrant_CreateCollection
            /// Response type for "Create".
            public typealias Output = Qdrant_CollectionOperationResponse
            /// Descriptor for "Create".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "Create"
            )
        }
        /// Namespace for "Update" metadata.
        public enum Update: Sendable {
            /// Request type for "Update".
            public typealias Input = Qdrant_UpdateCollection
            /// Response type for "Update".
            public typealias Output = Qdrant_CollectionOperationResponse
            /// Descriptor for "Update".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "Update"
            )
        }
        /// Namespace for "Delete" metadata.
        public enum Delete: Sendable {
            /// Request type for "Delete".
            public typealias Input = Qdrant_DeleteCollection
            /// Response type for "Delete".
            public typealias Output = Qdrant_CollectionOperationResponse
            /// Descriptor for "Delete".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "Delete"
            )
        }
        /// Namespace for "UpdateAliases" metadata.
        public enum UpdateAliases: Sendable {
            /// Request type for "UpdateAliases".
            public typealias Input = Qdrant_ChangeAliases
            /// Response type for "UpdateAliases".
            public typealias Output = Qdrant_CollectionOperationResponse
            /// Descriptor for "UpdateAliases".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "UpdateAliases"
            )
        }
        /// Namespace for "ListCollectionAliases" metadata.
        public enum ListCollectionAliases: Sendable {
            /// Request type for "ListCollectionAliases".
            public typealias Input = Qdrant_ListCollectionAliasesRequest
            /// Response type for "ListCollectionAliases".
            public typealias Output = Qdrant_ListAliasesResponse
            /// Descriptor for "ListCollectionAliases".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "ListCollectionAliases"
            )
        }
        /// Namespace for "ListAliases" metadata.
        public enum ListAliases: Sendable {
            /// Request type for "ListAliases".
            public typealias Input = Qdrant_ListAliasesRequest
            /// Response type for "ListAliases".
            public typealias Output = Qdrant_ListAliasesResponse
            /// Descriptor for "ListAliases".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "ListAliases"
            )
        }
        /// Namespace for "CollectionClusterInfo" metadata.
        public enum CollectionClusterInfo: Sendable {
            /// Request type for "CollectionClusterInfo".
            public typealias Input = Qdrant_CollectionClusterInfoRequest
            /// Response type for "CollectionClusterInfo".
            public typealias Output = Qdrant_CollectionClusterInfoResponse
            /// Descriptor for "CollectionClusterInfo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "CollectionClusterInfo"
            )
        }
        /// Namespace for "CollectionExists" metadata.
        public enum CollectionExists: Sendable {
            /// Request type for "CollectionExists".
            public typealias Input = Qdrant_CollectionExistsRequest
            /// Response type for "CollectionExists".
            public typealias Output = Qdrant_CollectionExistsResponse
            /// Descriptor for "CollectionExists".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "CollectionExists"
            )
        }
        /// Namespace for "UpdateCollectionClusterSetup" metadata.
        public enum UpdateCollectionClusterSetup: Sendable {
            /// Request type for "UpdateCollectionClusterSetup".
            public typealias Input = Qdrant_UpdateCollectionClusterSetupRequest
            /// Response type for "UpdateCollectionClusterSetup".
            public typealias Output = Qdrant_UpdateCollectionClusterSetupResponse
            /// Descriptor for "UpdateCollectionClusterSetup".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "UpdateCollectionClusterSetup"
            )
        }
        /// Namespace for "CreateShardKey" metadata.
        public enum CreateShardKey: Sendable {
            /// Request type for "CreateShardKey".
            public typealias Input = Qdrant_CreateShardKeyRequest
            /// Response type for "CreateShardKey".
            public typealias Output = Qdrant_CreateShardKeyResponse
            /// Descriptor for "CreateShardKey".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "CreateShardKey"
            )
        }
        /// Namespace for "DeleteShardKey" metadata.
        public enum DeleteShardKey: Sendable {
            /// Request type for "DeleteShardKey".
            public typealias Input = Qdrant_DeleteShardKeyRequest
            /// Response type for "DeleteShardKey".
            public typealias Output = Qdrant_DeleteShardKeyResponse
            /// Descriptor for "DeleteShardKey".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "DeleteShardKey"
            )
        }
        /// Namespace for "ListShardKeys" metadata.
        public enum ListShardKeys: Sendable {
            /// Request type for "ListShardKeys".
            public typealias Input = Qdrant_ListShardKeysRequest
            /// Response type for "ListShardKeys".
            public typealias Output = Qdrant_ListShardKeysResponse
            /// Descriptor for "ListShardKeys".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections"),
                method: "ListShardKeys"
            )
        }
        /// Descriptors for all methods in the "qdrant.Collections" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Get.descriptor,
            List.descriptor,
            Create.descriptor,
            Update.descriptor,
            Delete.descriptor,
            UpdateAliases.descriptor,
            ListCollectionAliases.descriptor,
            ListAliases.descriptor,
            CollectionClusterInfo.descriptor,
            CollectionExists.descriptor,
            UpdateCollectionClusterSetup.descriptor,
            CreateShardKey.descriptor,
            DeleteShardKey.descriptor,
            ListShardKeys.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "qdrant.Collections" service.
    public static let qdrant_Collections = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Collections")
}

// MARK: qdrant.Collections (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Collections {
    /// Generated client protocol for the "qdrant.Collections" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Get" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get detailed information about specified existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_GetCollectionInfoRequest` message.
        ///   - serializer: A serializer for `Qdrant_GetCollectionInfoRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_GetCollectionInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func get<Result>(
            request: GRPCCore.ClientRequest<Qdrant_GetCollectionInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_GetCollectionInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_GetCollectionInfoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_GetCollectionInfoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "List" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of names of all existing collections
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListCollectionsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListCollectionsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListCollectionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func list<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListCollectionsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListCollectionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListCollectionsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListCollectionsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Create" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create new collection with given parameters
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateCollection` message.
        ///   - serializer: A serializer for `Qdrant_CreateCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func create<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Update" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update parameters of the existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_UpdateCollection` message.
        ///   - serializer: A serializer for `Qdrant_UpdateCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func update<Result>(
            request: GRPCCore.ClientRequest<Qdrant_UpdateCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_UpdateCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Delete" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Drop collection and all associated data
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteCollection` message.
        ///   - serializer: A serializer for `Qdrant_DeleteCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func delete<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update Aliases of the existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ChangeAliases` message.
        ///   - serializer: A serializer for `Qdrant_ChangeAliases` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ChangeAliases>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ChangeAliases>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListCollectionAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of all aliases for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListCollectionAliasesRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListCollectionAliasesRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListAliasesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listCollectionAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListCollectionAliasesRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListCollectionAliasesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListAliasesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of all aliases for all existing collections
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListAliasesRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListAliasesRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListAliasesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListAliasesRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListAliasesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListAliasesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CollectionClusterInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get cluster information for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CollectionClusterInfoRequest` message.
        ///   - serializer: A serializer for `Qdrant_CollectionClusterInfoRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionClusterInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func collectionClusterInfo<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CollectionClusterInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CollectionClusterInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionClusterInfoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionClusterInfoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CollectionExists" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Check the existence of a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CollectionExistsRequest` message.
        ///   - serializer: A serializer for `Qdrant_CollectionExistsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionExistsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func collectionExists<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CollectionExistsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CollectionExistsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionExistsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionExistsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateCollectionClusterSetup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update cluster setup for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_UpdateCollectionClusterSetupRequest` message.
        ///   - serializer: A serializer for `Qdrant_UpdateCollectionClusterSetupRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_UpdateCollectionClusterSetupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateCollectionClusterSetup<Result>(
            request: GRPCCore.ClientRequest<Qdrant_UpdateCollectionClusterSetupRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_UpdateCollectionClusterSetupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_UpdateCollectionClusterSetupResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_UpdateCollectionClusterSetupResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateShardKey" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create shard key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateShardKeyRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateShardKeyRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateShardKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createShardKey<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateShardKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateShardKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateShardKeyResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateShardKeyResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteShardKey" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete shard key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteShardKeyRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteShardKeyRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteShardKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteShardKey<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteShardKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteShardKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteShardKeyResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteShardKeyResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListShardKeys" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List shard keys
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListShardKeysRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListShardKeysRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListShardKeysResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listShardKeys<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListShardKeysRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListShardKeysRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListShardKeysResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListShardKeysResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "qdrant.Collections" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Get" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get detailed information about specified existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_GetCollectionInfoRequest` message.
        ///   - serializer: A serializer for `Qdrant_GetCollectionInfoRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_GetCollectionInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func get<Result>(
            request: GRPCCore.ClientRequest<Qdrant_GetCollectionInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_GetCollectionInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_GetCollectionInfoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_GetCollectionInfoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.Get.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "List" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of names of all existing collections
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListCollectionsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListCollectionsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListCollectionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func list<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListCollectionsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListCollectionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListCollectionsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListCollectionsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.List.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Create" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create new collection with given parameters
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateCollection` message.
        ///   - serializer: A serializer for `Qdrant_CreateCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func create<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.Create.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Update" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update parameters of the existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_UpdateCollection` message.
        ///   - serializer: A serializer for `Qdrant_UpdateCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func update<Result>(
            request: GRPCCore.ClientRequest<Qdrant_UpdateCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_UpdateCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.Update.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Delete" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Drop collection and all associated data
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteCollection` message.
        ///   - serializer: A serializer for `Qdrant_DeleteCollection` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func delete<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteCollection>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteCollection>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.Delete.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update Aliases of the existing collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ChangeAliases` message.
        ///   - serializer: A serializer for `Qdrant_ChangeAliases` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionOperationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ChangeAliases>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ChangeAliases>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionOperationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.UpdateAliases.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListCollectionAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of all aliases for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListCollectionAliasesRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListCollectionAliasesRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListAliasesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listCollectionAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListCollectionAliasesRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListCollectionAliasesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListAliasesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.ListCollectionAliases.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListAliases" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of all aliases for all existing collections
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListAliasesRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListAliasesRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListAliasesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listAliases<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListAliasesRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListAliasesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListAliasesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.ListAliases.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CollectionClusterInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get cluster information for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CollectionClusterInfoRequest` message.
        ///   - serializer: A serializer for `Qdrant_CollectionClusterInfoRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionClusterInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func collectionClusterInfo<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CollectionClusterInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CollectionClusterInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionClusterInfoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionClusterInfoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.CollectionClusterInfo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CollectionExists" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Check the existence of a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CollectionExistsRequest` message.
        ///   - serializer: A serializer for `Qdrant_CollectionExistsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CollectionExistsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func collectionExists<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CollectionExistsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CollectionExistsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CollectionExistsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionExistsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.CollectionExists.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateCollectionClusterSetup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Update cluster setup for a collection
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_UpdateCollectionClusterSetupRequest` message.
        ///   - serializer: A serializer for `Qdrant_UpdateCollectionClusterSetupRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_UpdateCollectionClusterSetupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateCollectionClusterSetup<Result>(
            request: GRPCCore.ClientRequest<Qdrant_UpdateCollectionClusterSetupRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_UpdateCollectionClusterSetupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_UpdateCollectionClusterSetupResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_UpdateCollectionClusterSetupResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.UpdateCollectionClusterSetup.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateShardKey" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create shard key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateShardKeyRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateShardKeyRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateShardKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createShardKey<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateShardKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateShardKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateShardKeyResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateShardKeyResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.CreateShardKey.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteShardKey" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete shard key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteShardKeyRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteShardKeyRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteShardKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteShardKey<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteShardKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteShardKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteShardKeyResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteShardKeyResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.DeleteShardKey.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListShardKeys" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List shard keys
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListShardKeysRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListShardKeysRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListShardKeysResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listShardKeys<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListShardKeysRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListShardKeysRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListShardKeysResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListShardKeysResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Collections.Method.ListShardKeys.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Collections.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get detailed information about specified existing collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_GetCollectionInfoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        request: GRPCCore.ClientRequest<Qdrant_GetCollectionInfoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_GetCollectionInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.get(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_GetCollectionInfoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_GetCollectionInfoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "List" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of names of all existing collections
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListCollectionsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func list<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListCollectionsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListCollectionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.list(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListCollectionsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListCollectionsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Create" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create new collection with given parameters
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CreateCollection` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func create<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CreateCollection>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.create(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CreateCollection>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionOperationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Update" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update parameters of the existing collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_UpdateCollection` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func update<Result>(
        request: GRPCCore.ClientRequest<Qdrant_UpdateCollection>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.update(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_UpdateCollection>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionOperationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Delete" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Drop collection and all associated data
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_DeleteCollection` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func delete<Result>(
        request: GRPCCore.ClientRequest<Qdrant_DeleteCollection>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.delete(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_DeleteCollection>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionOperationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update Aliases of the existing collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ChangeAliases` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateAliases<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ChangeAliases>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateAliases(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ChangeAliases>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionOperationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListCollectionAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of all aliases for a collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListCollectionAliasesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listCollectionAliases<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListCollectionAliasesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listCollectionAliases(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListCollectionAliasesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListAliasesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of all aliases for all existing collections
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListAliasesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listAliases<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListAliasesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listAliases(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListAliasesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListAliasesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CollectionClusterInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get cluster information for a collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CollectionClusterInfoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func collectionClusterInfo<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CollectionClusterInfoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionClusterInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.collectionClusterInfo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CollectionClusterInfoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionClusterInfoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CollectionExists" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Check the existence of a collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CollectionExistsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func collectionExists<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CollectionExistsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionExistsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.collectionExists(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CollectionExistsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CollectionExistsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateCollectionClusterSetup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update cluster setup for a collection
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_UpdateCollectionClusterSetupRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateCollectionClusterSetup<Result>(
        request: GRPCCore.ClientRequest<Qdrant_UpdateCollectionClusterSetupRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_UpdateCollectionClusterSetupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateCollectionClusterSetup(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_UpdateCollectionClusterSetupRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_UpdateCollectionClusterSetupResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateShardKey" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create shard key
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CreateShardKeyRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createShardKey<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CreateShardKeyRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateShardKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createShardKey(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CreateShardKeyRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CreateShardKeyResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteShardKey" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete shard key
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_DeleteShardKeyRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteShardKey<Result>(
        request: GRPCCore.ClientRequest<Qdrant_DeleteShardKeyRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteShardKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteShardKey(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_DeleteShardKeyRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_DeleteShardKeyResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListShardKeys" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List shard keys
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListShardKeysRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listShardKeys<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListShardKeysRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListShardKeysResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listShardKeys(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListShardKeysRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListShardKeysResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Collections.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get detailed information about specified existing collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        _ message: Qdrant_GetCollectionInfoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_GetCollectionInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_GetCollectionInfoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.get(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "List" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of names of all existing collections
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func list<Result>(
        _ message: Qdrant_ListCollectionsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListCollectionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListCollectionsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.list(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Create" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create new collection with given parameters
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func create<Result>(
        _ message: Qdrant_CreateCollection,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CreateCollection>(
            message: message,
            metadata: metadata
        )
        return try await self.create(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Update" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update parameters of the existing collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func update<Result>(
        _ message: Qdrant_UpdateCollection,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_UpdateCollection>(
            message: message,
            metadata: metadata
        )
        return try await self.update(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Delete" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Drop collection and all associated data
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func delete<Result>(
        _ message: Qdrant_DeleteCollection,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_DeleteCollection>(
            message: message,
            metadata: metadata
        )
        return try await self.delete(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update Aliases of the existing collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateAliases<Result>(
        _ message: Qdrant_ChangeAliases,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionOperationResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ChangeAliases>(
            message: message,
            metadata: metadata
        )
        return try await self.updateAliases(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListCollectionAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of all aliases for a collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listCollectionAliases<Result>(
        _ message: Qdrant_ListCollectionAliasesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListCollectionAliasesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listCollectionAliases(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListAliases" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of all aliases for all existing collections
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listAliases<Result>(
        _ message: Qdrant_ListAliasesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListAliasesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListAliasesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listAliases(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CollectionClusterInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get cluster information for a collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func collectionClusterInfo<Result>(
        _ message: Qdrant_CollectionClusterInfoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionClusterInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CollectionClusterInfoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.collectionClusterInfo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CollectionExists" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Check the existence of a collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func collectionExists<Result>(
        _ message: Qdrant_CollectionExistsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CollectionExistsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CollectionExistsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.collectionExists(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateCollectionClusterSetup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Update cluster setup for a collection
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateCollectionClusterSetup<Result>(
        _ message: Qdrant_UpdateCollectionClusterSetupRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_UpdateCollectionClusterSetupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_UpdateCollectionClusterSetupRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateCollectionClusterSetup(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateShardKey" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create shard key
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createShardKey<Result>(
        _ message: Qdrant_CreateShardKeyRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateShardKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CreateShardKeyRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createShardKey(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteShardKey" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete shard key
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteShardKey<Result>(
        _ message: Qdrant_DeleteShardKeyRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteShardKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_DeleteShardKeyRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteShardKey(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListShardKeys" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List shard keys
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listShardKeys<Result>(
        _ message: Qdrant_ListShardKeysRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListShardKeysResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListShardKeysRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listShardKeys(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}