/// source: https://github.com/grpc/grpc/blob/master/doc/health-checking.md#service-definition

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: health_check.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - grpc.health.v1.Health

/// Namespace containing generated types for the "grpc.health.v1.Health" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Grpc_Health_V1_Health: Sendable {
    /// Service descriptor for the "grpc.health.v1.Health" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "grpc.health.v1.Health")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Check" metadata.
        public enum Check: Sendable {
            /// Request type for "Check".
            public typealias Input = Grpc_Health_V1_HealthCheckRequest
            /// Response type for "Check".
            public typealias Output = Grpc_Health_V1_HealthCheckResponse
            /// Descriptor for "Check".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "grpc.health.v1.Health"),
                method: "Check"
            )
        }
        /// Descriptors for all methods in the "grpc.health.v1.Health" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Check.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "grpc.health.v1.Health" service.
    public static let grpc_health_v1_Health = GRPCCore.ServiceDescriptor(fullyQualifiedService: "grpc.health.v1.Health")
}

// MARK: grpc.health.v1.Health (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Grpc_Health_V1_Health {
    /// Generated client protocol for the "grpc.health.v1.Health" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Grpc_Health_V1_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Grpc_Health_V1_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Grpc_Health_V1_HealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func check<Result>(
            request: GRPCCore.ClientRequest<Grpc_Health_V1_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Grpc_Health_V1_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Grpc_Health_V1_HealthCheckResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Grpc_Health_V1_HealthCheckResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "grpc.health.v1.Health" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Grpc_Health_V1_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Grpc_Health_V1_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Grpc_Health_V1_HealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func check<Result>(
            request: GRPCCore.ClientRequest<Grpc_Health_V1_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Grpc_Health_V1_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Grpc_Health_V1_HealthCheckResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Grpc_Health_V1_HealthCheckResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Grpc_Health_V1_Health.Method.Check.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Grpc_Health_V1_Health.ClientProtocol {
    /// Call the "Check" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Grpc_Health_V1_HealthCheckRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func check<Result>(
        request: GRPCCore.ClientRequest<Grpc_Health_V1_HealthCheckRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Grpc_Health_V1_HealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.check(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Grpc_Health_V1_HealthCheckRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Grpc_Health_V1_HealthCheckResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Grpc_Health_V1_Health.ClientProtocol {
    /// Call the "Check" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func check<Result>(
        _ message: Grpc_Health_V1_HealthCheckRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Grpc_Health_V1_HealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Grpc_Health_V1_HealthCheckRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.check(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}