// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: qdrant.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - qdrant.Qdrant

/// Namespace containing generated types for the "qdrant.Qdrant" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Qdrant_Qdrant: Sendable {
    /// Service descriptor for the "qdrant.Qdrant" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Qdrant")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "HealthCheck" metadata.
        public enum HealthCheck: Sendable {
            /// Request type for "HealthCheck".
            public typealias Input = Qdrant_HealthCheckRequest
            /// Response type for "HealthCheck".
            public typealias Output = Qdrant_HealthCheckReply
            /// Descriptor for "HealthCheck".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Qdrant"),
                method: "HealthCheck"
            )
        }
        /// Descriptors for all methods in the "qdrant.Qdrant" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            HealthCheck.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "qdrant.Qdrant" service.
    public static let qdrant_Qdrant = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Qdrant")
}

// MARK: qdrant.Qdrant (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Qdrant {
    /// Generated client protocol for the "qdrant.Qdrant" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "HealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Qdrant_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_HealthCheckReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func healthCheck<Result>(
            request: GRPCCore.ClientRequest<Qdrant_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_HealthCheckReply>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_HealthCheckReply>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "qdrant.Qdrant" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "HealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Qdrant_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_HealthCheckReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func healthCheck<Result>(
            request: GRPCCore.ClientRequest<Qdrant_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_HealthCheckReply>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_HealthCheckReply>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Qdrant.Method.HealthCheck.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Qdrant.ClientProtocol {
    /// Call the "HealthCheck" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_HealthCheckRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func healthCheck<Result>(
        request: GRPCCore.ClientRequest<Qdrant_HealthCheckRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_HealthCheckReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.healthCheck(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_HealthCheckRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_HealthCheckReply>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Qdrant.ClientProtocol {
    /// Call the "HealthCheck" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func healthCheck<Result>(
        _ message: Qdrant_HealthCheckRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_HealthCheckReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_HealthCheckRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.healthCheck(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}