// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: snapshots_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - qdrant.Snapshots

/// Namespace containing generated types for the "qdrant.Snapshots" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Qdrant_Snapshots: Sendable {
    /// Service descriptor for the "qdrant.Snapshots" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Create" metadata.
        public enum Create: Sendable {
            /// Request type for "Create".
            public typealias Input = Qdrant_CreateSnapshotRequest
            /// Response type for "Create".
            public typealias Output = Qdrant_CreateSnapshotResponse
            /// Descriptor for "Create".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "Create"
            )
        }
        /// Namespace for "List" metadata.
        public enum List: Sendable {
            /// Request type for "List".
            public typealias Input = Qdrant_ListSnapshotsRequest
            /// Response type for "List".
            public typealias Output = Qdrant_ListSnapshotsResponse
            /// Descriptor for "List".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "List"
            )
        }
        /// Namespace for "Delete" metadata.
        public enum Delete: Sendable {
            /// Request type for "Delete".
            public typealias Input = Qdrant_DeleteSnapshotRequest
            /// Response type for "Delete".
            public typealias Output = Qdrant_DeleteSnapshotResponse
            /// Descriptor for "Delete".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "Delete"
            )
        }
        /// Namespace for "CreateFull" metadata.
        public enum CreateFull: Sendable {
            /// Request type for "CreateFull".
            public typealias Input = Qdrant_CreateFullSnapshotRequest
            /// Response type for "CreateFull".
            public typealias Output = Qdrant_CreateSnapshotResponse
            /// Descriptor for "CreateFull".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "CreateFull"
            )
        }
        /// Namespace for "ListFull" metadata.
        public enum ListFull: Sendable {
            /// Request type for "ListFull".
            public typealias Input = Qdrant_ListFullSnapshotsRequest
            /// Response type for "ListFull".
            public typealias Output = Qdrant_ListSnapshotsResponse
            /// Descriptor for "ListFull".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "ListFull"
            )
        }
        /// Namespace for "DeleteFull" metadata.
        public enum DeleteFull: Sendable {
            /// Request type for "DeleteFull".
            public typealias Input = Qdrant_DeleteFullSnapshotRequest
            /// Response type for "DeleteFull".
            public typealias Output = Qdrant_DeleteSnapshotResponse
            /// Descriptor for "DeleteFull".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots"),
                method: "DeleteFull"
            )
        }
        /// Descriptors for all methods in the "qdrant.Snapshots" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Create.descriptor,
            List.descriptor,
            Delete.descriptor,
            CreateFull.descriptor,
            ListFull.descriptor,
            DeleteFull.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "qdrant.Snapshots" service.
    public static let qdrant_Snapshots = GRPCCore.ServiceDescriptor(fullyQualifiedService: "qdrant.Snapshots")
}

// MARK: qdrant.Snapshots (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Snapshots {
    /// Generated client protocol for the "qdrant.Snapshots" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Create" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create collection snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func create<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateSnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "List" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List collection snapshots
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListSnapshotsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListSnapshotsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListSnapshotsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func list<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListSnapshotsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListSnapshotsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListSnapshotsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Delete" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete collection snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func delete<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteSnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create full storage snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateFullSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateFullSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateFullSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateFullSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateSnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List full storage snapshots
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListFullSnapshotsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListFullSnapshotsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListSnapshotsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListFullSnapshotsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListFullSnapshotsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListSnapshotsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete full storage snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteFullSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteFullSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteFullSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteFullSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteSnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "qdrant.Snapshots" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Create" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create collection snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func create<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateSnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.Create.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "List" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List collection snapshots
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListSnapshotsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListSnapshotsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListSnapshotsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func list<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListSnapshotsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListSnapshotsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListSnapshotsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.List.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Delete" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete collection snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func delete<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteSnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.Delete.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create full storage snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_CreateFullSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_CreateFullSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_CreateSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_CreateFullSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_CreateFullSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_CreateSnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.CreateFull.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List full storage snapshots
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_ListFullSnapshotsRequest` message.
        ///   - serializer: A serializer for `Qdrant_ListFullSnapshotsRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_ListSnapshotsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_ListFullSnapshotsRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_ListFullSnapshotsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_ListSnapshotsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.ListFull.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteFull" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Delete full storage snapshot
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Qdrant_DeleteFullSnapshotRequest` message.
        ///   - serializer: A serializer for `Qdrant_DeleteFullSnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Qdrant_DeleteSnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteFull<Result>(
            request: GRPCCore.ClientRequest<Qdrant_DeleteFullSnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Qdrant_DeleteFullSnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Qdrant_DeleteSnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Qdrant_Snapshots.Method.DeleteFull.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Snapshots.ClientProtocol {
    /// Call the "Create" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create collection snapshot
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CreateSnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func create<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CreateSnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.create(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CreateSnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CreateSnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "List" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List collection snapshots
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListSnapshotsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func list<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListSnapshotsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.list(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListSnapshotsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListSnapshotsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Delete" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete collection snapshot
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_DeleteSnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func delete<Result>(
        request: GRPCCore.ClientRequest<Qdrant_DeleteSnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.delete(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_DeleteSnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_DeleteSnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create full storage snapshot
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_CreateFullSnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createFull<Result>(
        request: GRPCCore.ClientRequest<Qdrant_CreateFullSnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createFull(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_CreateFullSnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_CreateSnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List full storage snapshots
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_ListFullSnapshotsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listFull<Result>(
        request: GRPCCore.ClientRequest<Qdrant_ListFullSnapshotsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listFull(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_ListFullSnapshotsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_ListSnapshotsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete full storage snapshot
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Qdrant_DeleteFullSnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteFull<Result>(
        request: GRPCCore.ClientRequest<Qdrant_DeleteFullSnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteFull(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Qdrant_DeleteFullSnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Qdrant_DeleteSnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Qdrant_Snapshots.ClientProtocol {
    /// Call the "Create" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create collection snapshot
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func create<Result>(
        _ message: Qdrant_CreateSnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CreateSnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.create(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "List" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List collection snapshots
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func list<Result>(
        _ message: Qdrant_ListSnapshotsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListSnapshotsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.list(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Delete" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete collection snapshot
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func delete<Result>(
        _ message: Qdrant_DeleteSnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_DeleteSnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.delete(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create full storage snapshot
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createFull<Result>(
        _ message: Qdrant_CreateFullSnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_CreateSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_CreateFullSnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createFull(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List full storage snapshots
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listFull<Result>(
        _ message: Qdrant_ListFullSnapshotsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_ListSnapshotsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_ListFullSnapshotsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listFull(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteFull" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Delete full storage snapshot
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteFull<Result>(
        _ message: Qdrant_DeleteFullSnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Qdrant_DeleteSnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Qdrant_DeleteFullSnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteFull(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}